Theodore's Pizza Shop/force-app/main/default/objects/tps_Pizza__c/tps_Pizza__c.object-meta.xml
<CustomObject>
    <label>Pizza</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Pizza Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizzas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Theodore's Pizza Shop/force-app/main/default/objects/tps_Pizza__c/fields/tps_Pizza_Order__c.field-meta.xml
<CustomField>
    <fullName>tps_Pizza_Order__c</fullName>
    <label>Pizza Order</label>
    <referenceTo>tps_Pizza_Order__c</referenceTo>
    <relationshipLabel>Pizzas</relationshipLabel>
    <relationshipName>Pizzas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Theodore's Pizza Shop/force-app/main/default/objects/tps_Pizza_Order__c/tps_Pizza_Order__c.object-meta.xml
<CustomObject>
    <label>Pizza Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Pizza Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizza Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Theodore's Pizza Shop/force-app/main/default/objects/tps_Pizza_Order__c/fields/tps_Contact__c.field-meta.xml
<CustomField>
    <fullName>tps_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pizza Orders</relationshipLabel>
    <relationshipName>Pizza_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Theodore's Pizza Shop/force-app/main/default/classes/tps_PizzaOrderController.cls
public with sharing class tps_PizzaOrderController {
    
    @AuraEnabled
    public static Id createPizzaOrder(Id contactId) {

        System.debug('ContactId: ' + contactId);
        
        tps_Pizza_Order__c newOrder = new tps_Pizza_Order__c();
        newOrder.tps_Contact__c = contactId;
        insert newOrder;
        return newOrder.Id;

    }

    @AuraEnabled
    public static void submitPizzas(Id pizzaOrderId, List<tps_Pizza__c> pizzaList) {
        
        for (tps_Pizza__c pizza : pizzaList) {
            pizza.tps_Pizza_Order__c = pizzaOrderId;
        }
        insert pizzaList;

    }

}